tmp

diff --git a/bin/rpush-local b/bin/rpush-local
--- a/bin/rpush-local
+++ b/bin/rpush-local
@@ -1,3 +1,12 @@
 #!/bin/sh
-
-rsync -av --partial --progress --exclude "node_modules" --rsh="ssh -p 22" $(pwd) eddie@192.168.21.86:/mnt/d/rsync  --delete
+while [ 1 ]
+do
+    rsync -av --partial --progress --exclude "node_modules" --rsh="ssh -p 22" $(pwd) eddie@192.168.21.86:/mnt/d/rsync  --delete
+    if [ "$?" = "0" ] ; then
+        echo "rsync completed normally"
+        exit
+    else
+        echo "Rsync failure. Backing off and retrying..."
+        sleep 180
+    fi
+done
